digiclaim/auth/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'auth'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

digiclaim/detection/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'detection'

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^updateProfile/$', views.updateProfile, name='updateProfile'),
    url(r'^scratchDetection/$', views.scratchDetection, name='scratchDetection'),
    url(r'^claimInfo/(?P<claim_id>[0-9a-z]+)/$', views.claimInfo, name='claimInfo'),
]

digiclaim/digiclaim/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^auth/', include('auth.urls')),
    url(r'^detection/', include('detection.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digiclaim/detection/models.py
from django.db import models
import secrets


class UserData(models.Model):
    email = models.EmailField(max_length=100, primary_key=True)
    username = models.CharField(max_length=100)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mobile = models.CharField(max_length=100)
    address = models.TextField(max_length=1000)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)

    def __str__(self):
        return self.email + '--' + self.username


class Claim(models.Model):
    claim_id = models.CharField(max_length=100, primary_key=True)
    user_id = models.CharField(max_length=100, default="")
    model_name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100, default="")
    device_image = models.FileField(default="")

    def setClaimId(self):
        self.course_id = secrets.token_hex(8)
        return self.course_id

    def __str__(self):
        return self.claim_id + "--" + self.model_name


class ProcessedClaim(models.Model):
    claim_id = models.CharField(max_length=100, primary_key=True)
    initial_image = models.FileField(default="")
    image_denoised = models.FileField(default="")
    image_l1 = models.FileField(default="")
    image_l2 = models.FileField(default="")
    scratch_flag = models.BooleanField(default=False)

    def __str__(self):
        return self.claim_id

digiclaim/detection/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
import pyrebase
import cv2
import matplotlib.pyplot as plt
from .models import UserData, Claim, ProcessedClaim
from django.core.files.base import ContentFile


config = {
    'apiKey': "AIzaSyDkQWQjchqJICUemhhKDdDwOWYuDs1Fhwc",
    'authDomain': "digiclaiminsurance.firebaseapp.com",
    'databaseURL': "https://digiclaiminsurance.firebaseio.com",
    'projectId': "digiclaiminsurance",
    'storageBucket': "digiclaiminsurance.appspot.com",
    'messagingSenderId': "615762764001"
};
firebase = pyrebase.initialize_app(config);
auth = firebase.auth()
database = firebase.database()
storage = firebase.storage()



def get_current_user(request):
    uid = request.session['uid']
    user = auth.get_account_info(uid)
    return user['users'][0]

def get_no_of_users(request):
    users = database.child('users').get().val()
    return len(users)


def dashboard(request):
    user = get_current_user(request)
    no_of_users = get_no_of_users(request)

    claims = Claim.objects.filter(user_id=user['localId'])
    claim_count = Claim.objects.count()
    p_claim_count = ProcessedClaim.objects.count()

    context = {
        'user': user,
        'page': 'dashboard',
        'claims': claims,
        'claim_count': claim_count,
        'p_claim_count': p_claim_count,
        'no_of_users': no_of_users
    }
    return render(request, 'dashboard.html', context)


def updateProfile(request):
    user = get_current_user(request)
    if request.method == 'POST':
        user_data = {
            'username': request.POST['username'],
            'first_name': request.POST['firstName'],
            'last_name': request.POST['lastName'],
            'mobile': request.POST['mobile'],
            'email': request.POST['email'],
            'city': request.POST['city'],
            'state': request.POST['state'],
            'address': request.POST['address'],
        }

        database.child('users').child(user['localId']).child('details').set(user_data)

        return dashboard(request)
    else:
        context = {
            'user': user
        }
        return render(request, 'profile.html', context)


def scratchDetection(request):
    user = get_current_user(request)
    if request.method == 'POST' and request.FILES['image']:
        new_claim = Claim()
        new_claim.claim_id = new_claim.setClaimId()
        new_claim.user_id = user['localId']
        new_claim.model_name = request.POST['name']
        new_claim.brand = request.POST['brand']
        new_claim.device_image = request.FILES['image']
        new_claim.save()

        claim = Claim.objects.filter(claim_id=new_claim.claim_id)[0]

        imgpath = '/home/thephenom1708/DigiClaim/digiclaim' + claim.device_image.url

        img = cv2.imread(imgpath, 0)
        denoised = cv2.medianBlur(img, 3)

        L1 = cv2.Canny(denoised, 50, 300, L2gradient=False)

        L2 = cv2.Canny(denoised, 100, 150, L2gradient=True)

        titles = ['Original Image', 'L1 Norm', 'L2 Norm', 'Denoised']

        outputs = [img, L1, L2, denoised]

        #cv2.imwrite("../images/" + claim.claim_id + '_' + 'pre_L1.jpeg', L1)
        #cv2.imwrite("../images/" + claim.claim_id + '_' + 'pre_L2.jpeg', L2)

        for i in range(4):
            plt.subplot(1, 4, i + 1)
            plt.imshow(outputs[i], cmap='gray')
            plt.title(titles[i])
            plt.xticks([])
            plt.yticks([])
        plt.show()
        print(type(L1))
        z = L1.shape
        print(z)
        uplimit = (z[0] * 13) // 100
        for i in range(z[0]):
            for j in range(z[1]):
                if L1[i][j] > 150:
                    L1[i][j] = 255
                else:
                    L1[i][j] = 0

        y = L2.shape
        for i in range(y[0]):
            for j in range(y[1]):
                if L2[i][j] > 150:
                    L2[i][j] = 255
                else:
                    L2[i][j] = 0

        count = 0
        totcount = 0;
        print(y)
        for i in range(uplimit, z[0] - uplimit):
            for j in range(15, z[1] - 15):
                totcount = totcount + 1;
                if L1[i][j] == 255:
                    print(str(i) + " " + str(j) + " " + str(L1[i][j]))
                    count = count + 1

        print("Count " + str(count))
        print("Total " + str(totcount))
        z = L1.shape
        print(z)
        print(uplimit)
        print(z[0] - uplimit)

        flag = False
        if count > 100:
            flag = True
            print("Scratch on Screen")
        else:
            flag = False
            print("Scratch not present on screen")

        cv2.imwrite("/home/DigiClaim/digiclaim/images/" + claim.claim_id + '_' + 'denoised.jpeg', denoised)
        cv2.imwrite("/home/DigiClaim/digiclaim/images/" + claim.claim_id + '_' + 'L1.jpeg', L1)
        cv2.imwrite("/home/DigiClaim/digiclaim/images/" + claim.claim_id + '_' + 'L2.jpeg', L2)

        denoised_img = open("/home/DigiClaim/digiclaim/images/" + claim.claim_id + '_' + 'denoised.jpeg', 'rb')
        l1 = open("/home/DigiClaim/digiclaim/images/" + claim.claim_id + '_' + 'L1.jpeg', 'rb')
        l2 = open("/home/DigiClaim/digiclaim/images/" + claim.claim_id + '_' + 'L2.jpeg', 'rb')

        denoised_content = ContentFile(denoised_img.read())
        l1_content = ContentFile(l1.read())
        l2_content = ContentFile(l2.read())

        new_processed_claim = ProcessedClaim()
        new_processed_claim.claim_id = claim.claim_id
        new_processed_claim.initial_image = claim.device_image
        new_processed_claim.scratch_flag = flag

        new_processed_claim.image_denoised.save(claim.claim_id + '_' + 'denoised.jpeg', denoised_content)
        new_processed_claim.image_l1.save(claim.claim_id + '_' + 'L1.jpeg', l1_content)
        new_processed_claim.image_l2.save(claim.claim_id + '_' + 'L2.jpeg', l2_content)

        new_processed_claim.save()

        device_data = database.child('users').child(user['localId']).child('PhoneAttributes').get().val()

        pdf = storage.child(user['localId'] + '/PDF').get_url(None)

        context = {
            'user': user,
            'flag': flag,
            'claim': new_claim,
            'processed_claim': new_processed_claim,
            'brand': device_data['Brand'],
            'sdk': device_data['SDK'],
            'model_id': device_data['Id'],
            'version_code': device_data['Version Code'],
            'pdf': pdf,
            'page': 'scratchDetection'
        }
        return render(request, 'result.html', context)

    else:
        context = {
            'user': user,
            'page': 'scratchDetection'
        }
        return render(request, 'scratchDetection.html', context)


def claimInfo(request, claim_id):
    user = get_current_user(request)
    claim = Claim.objects.filter(claim_id=claim_id)
    processed_claim = ProcessedClaim.objects.filter(claim_id=claim_id)

    device_data = database.child('users').child(user['localId']).child('PhoneAttributes').get().val()

    pdf = storage.child(user['localId'] + '/PDF').get_url(None)

    context = {
        'user': user,
        'flag': processed_claim[0].scratch_flag,
        'claim': claim[0],
        'processed_claim': processed_claim[0],
        'brand': device_data['Brand'],
        'sdk': device_data['SDK'],
        'model_id': device_data['Id'],
        'version_code': device_data['Version Code'],
        'pdf':pdf,
        'page': 'scratchDetection'
    }

    return render(request, 'result.html', context)

digiclaim/detection/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% load static %}
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png">
  <link rel='icon' type="image/png" href="{% static 'img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>{% block title %}
    User Dashboard
      {% endblock %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
    {% block head %}
    {% endblock %}
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="{% static 'img/sidebar-1.jpg' %}">

      <div class="logo">
        <a href="#" class="simple-text logo-normal">
          DigiClaim
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
            {% if page == 'dashboard' %}
            <li class="nav-item active ">
            {% else %}
             <li class="nav-item">
            {% endif %}
            <a class="nav-link" href="{% url 'detection:dashboard' %}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          {% if page == 'scratchDetection' %}
            <li class="nav-item active ">
            {% else %}
             <li class="nav-item">
            {% endif %}
            <a class="nav-link" href="{% url 'detection:scratchDetection' %}">
              <i class="material-icons">assignment</i>
              <p>Scratch Detection</p>
            </a>
          </li>

        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    <h3 class="dropdown-item">Welcome {{ user.name }}</h3>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'auth:logout' %}">Log out</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
        {% block body %}
    {% endblock %}

    </div>
  </div>



    <!--   Core JS Files   -->
  <script src="{% static 'js/core/jquery.min.js' %}"></script>
' %}  <script src="{% static 'js/core/popper.min.js' %}"></script>
' %}  <script src="{% static 'js/core/bootstrap-material-design.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Plugin for the momentJs  -->
  <script src="{% static 'js/plugins/moment.min.js' %}"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="{% static 'js/plugins/sweetalert2.js' %}"></script>
  <!-- Forms Validations Plugin -->
  <script src="{% static 'js/plugins/jquery.validate.min.js' %}"></script>
  <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="{% static 'js/plugins/jquery.bootstrap-wizard.js' %}"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="{% static 'js/plugins/bootstrap-selectpicker.js' %}"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="{% static 'js/plugins/bootstrap-datetimepicker.min.js' %}"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
  <script src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="{% static 'js/plugins/bootstrap-tagsinput.js' %}"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="{% static 'js/plugins/jasny-bootstrap.min.js' %}"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="{% static 'js/plugins/fullcalendar.min.js' %}"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="{% static 'js/plugins/jquery-jvectormap.js' %}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'js/plugins/nouislider.min.js' %}"></script>
  <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <script src="{% static 'js/plugins/arrive.min.js' %}"></script>
  <!-- Library for adding dinamically elements -->

  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="{% static 'js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.js' %}" type="text/javascript"></script>
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'demo/demo.js' %}"></script>
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>

</body>
</html>

digiclaim/detection/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}Student Portal{% endblock %}
{% load static %}
{% block body %}

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-4 col-md-6 col-sm-6">
				<div class="card card-stats">
					<div class="card-header card-header-warning card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment</i>
						</div>
						<p class="card-category">Total Claims</p><br>
						<h3 class="card-title">{{ claim_count }}</h3>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 col-sm-6">
				<div class="card card-stats">
					<div class="card-header card-header-success card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assignment_ind</i>
						</div>
						<p class="card-category">Total Users</p><br>
						<h3 class="card-title">{{ no_of_users }}</h3>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 col-sm-6">
				<div class="card card-stats">
					<div class="card-header card-header-danger card-header-icon">
						<div class="card-icon">
							<i class="material-icons">assessment</i>
						</div>
						<p class="card-category">Total Processed Claims</p><br>
						<h3 class="card-title">{{ p_claim_count }}</h3>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Courses -->
	<div class="row">
		{% for claim in claims %}
		<div class="col-md-4">
			<div class="card card-chart">
				<div class="card-header card-header-success">
					<div>
						<img class="card-img-bottom" src="{{ claim.device_image.url }}" alt="Card image" style="width:100%; height:400px">
					</div>
				</div>
				<div class="card-body">
					<h4 class="card-title">{{ claim.model_name }}</h4>
					<p class="card-category">{{ claim.brand }}</p>
				</div>
				<div class="card-footer">
					<div class="stats">
						<a href="{% url 'detection:claimInfo' claim.claim_id %}" class="btn btn-primary">Show details</a>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>

</div>
</div>
{% endblock %}

digiclaim/detection/templates/profile.html
{% extends 'base.html' %}
{% block title %}User Profile{% endblock %}
{% load static %}
{% block body %}

<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header card-header-primary">
						<h4 class="card-title">User Profile</h4>
						<p class="card-category">Personal Information</p>
					</div>
					<div class="card-body">
						<form method="POST" action="{% url 'detection:updateProfile' %}" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label class="bmd-label-floating">Username</label>
										<input type="text" name="username" class="form-control">
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label class="bmd-label-floating">First Name</label>
										<input type="text" name="firstName" class="form-control">
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label class="bmd-label-floating">Last Name</label>
										<input type="text" name="lastName" class="form-control">
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label class="bmd-label-floating">Mobile Number</label>
										<input type="text" class="form-control" name="mobile">
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label class="bmd-label-floating">Email ID</label>
										<input type="email" class="form-control" name="email" value="{{ user.email }}" readonly>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label class="bmd-label-floating">City</label>
										<input type="text" class="form-control" name="city">
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label class="bmd-label-floating">State</label>
										<input type="text" class="form-control" name="state">
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label>Address</label>
										<div class="form-group">
											<label class="bmd-label-floating"></label>
											<textarea class="form-control" rows="3" name="address"></textarea>
										</div>
									</div>
								</div>
							</div>

							<input type="submit" class="btn btn-primary pull-right" value="Update Info">
							<div class="clearfix"></div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}